/**
 * 從 SA §6.2 權限目錄機械產生 packages/contracts/src/permissions.generated.ts。
 * 與 migrations/0012_seed_permissions.sql 同源，確保 DB seed、程式碼、文件三者不漂移。
 *
 * 執行：npm run gen:permissions
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const root = fileURLToPath(new URL('..', import.meta.url));
const SA = `${root}docs/sa/Interactive_AI_Coach_SA_v1.0.md`;
const OUT = `${root}packages/contracts/src/permissions.generated.ts`;

const text = readFileSync(SA, 'utf8');
const start = text.indexOf('## 6.2 Permission');
const end = text.indexOf('## 6.3 ', start);
if (start < 0 || end < 0) throw new Error('SA §6.2 not found');
const section = text.slice(start, end);

const row = /^\| `([a-z][a-z_.]+)` \| ([^|]+?) \| ([a-z]+) \| ([^|]*?) \|$/gm;
const perms: { code: string; description: string; minScope: string; capability: string | null }[] = [];
for (const m of section.matchAll(row)) {
  const [, code, desc, scope, cap] = m as unknown as [string, string, string, string, string];
  const c = cap.replace(/`/g, '').trim();
  perms.push({
    code,
    description: desc.replace(/\*\*|`/g, '').trim(),
    minScope: scope,
    capability: c === '—' || c === '-' || c === '' ? null : c.split('+')[0]!.trim(),
  });
}

// 防呆：抓不到的列代表 SA 表格格式被改壞
const loose = [...section.matchAll(/^\| `([a-z][a-z_.]+)`/gm)].map((m) => m[1]);
const missed = loose.filter((c) => !perms.some((p) => p.code === c));
if (missed.length) throw new Error(`unparseable SA rows: ${missed.join(', ')}`);
if (new Set(perms.map((p) => p.code)).size !== perms.length) throw new Error('duplicate permission code in SA');

const body = `/* eslint-disable */
// ============================================================================
// AUTO-GENERATED by tools/gen-permissions.ts from SA §6.2 — DO NOT EDIT BY HAND.
// 修改權限：先改 SA，再執行 npm run gen:permissions
// ============================================================================

export const PERMISSIONS = {
${perms
  .map(
    (p) =>
      `  ${JSON.stringify(p.code)}: { minScope: ${JSON.stringify(p.minScope)}, capability: ${JSON.stringify(
        p.capability,
      )}, description: ${JSON.stringify(p.description)} },`,
  )
  .join('\n')}
} as const;

export type PermissionCode = keyof typeof PERMISSIONS;

export const PERMISSION_CODES = Object.keys(PERMISSIONS) as PermissionCode[];
`;

writeFileSync(OUT, body, 'utf8');
console.log(`generated ${perms.length} permissions -> ${OUT.replace(root, '')}`);
